.github/workflows/release.yml

Fix branch name.
Resolves #3
Not tested

fix: branch name

---

src/handlers/notify.rs
src/websocket_service/handlers/notify_delete.rs
src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_update.rs
tests/integration.rs

- Update msg TTLs as per https://github.com/WalletConnect/walletconnect-specs/pull/122
- Fix mis-computation of msg_id for log and analytics output.
Resolves #36

feat: update msg TTLs & fix msg_id

---

src/auth.rs
src/handlers/notify.rs
src/lib.rs
src/spec.rs
src/websocket_service/handlers/notify_delete.rs
src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_update.rs
src/websocket_service/mod.rs
tests/integration.rs

Refactor tags and TTLs into a spec file for easy reference.
Fix a number of TTLs that were incorrect.
Resolves #59
Locally

chore: spec constants

---

terraform/monitoring/panels/panels.libsonnet
terraform/vars/prod.tfvars

Reduce threshold as per this thread: https://walletconnect.slack.com/archives/C058RS0MH38/p1692548822748369?thread_ts=1692448085.704979&cid=C058RS0MH38
Resolves #68
Dev deployment

fix: DocumentDB available memory alarm

---

src/auth.rs
src/websocket_service/handlers/notify_delete.rs
src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_update.rs

Forgot to verify the resources in #65. Doing that here.
Resolves #71

fix: verify CACAO resources

---

src/handlers/notify.rs

Catches publish errors, not just timeouts.
Resolves #81

fix: catch publish error

---

src/handlers/notify.rs
src/metrics.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/app/notify_latency.libsonnet
terraform/monitoring/panels/app/subscribe_latency.libsonnet
terraform/monitoring/panels/panels.libsonnet

Add notify latency panel to Grafana.
Also fix soft max of subscribe latency panel as unit is `ms` not `s`.
Resolves #83
By hand with prod dashboard

feat: notify latency panel

---

terraform/monitoring/panels/lb/error_4xx.libsonnet

fix: refId

---

.github/workflows/cd.yml
.github/workflows/deploy-infra.yml
src/handlers/notify.rs

- Retries publishing up to 10 times. Related to https://walletconnect.slack.com/archives/C03SMNKLPU0/p1694704186740059
- Only send analytics export after successful publish, not before
Resolves #106
Not tested

fix: retry publishing

---

src/auth.rs
src/websocket_service/handlers/notify_watch_subscriptions.rs
src/websocket_service/mod.rs

- Fix expiration of watchers according to the spec
- Log message ID
- Make signature validation errors more visible
Resolves #115
Not tested

fix: watch subscriptions duration

---

Cargo.lock
Cargo.toml
src/analytics/mod.rs
src/config.rs
src/handlers/notify.rs
src/lib.rs
src/main.rs
src/state.rs
terraform/ecs/main.tf

Integrates the geoblocking feature from utils-rs. Currently blocked countries: KP, IR, CU, SY.

feat: geo-blocking, replace `gorgon` with `utils-rs`

---

src/auth.rs
src/error.rs
src/handlers/notify.rs
src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_watch_subscriptions.rs
tests/integration.rs

Update SIWE validation as per the [specs](https://github.com/WalletConnect/walletconnect-specs/pull/149)
It is also backwards-compatible with the previous spec revision.
Edits to notify_subscribe.rs and notify.rs are unrelated, but are included in this PR.
Resolves #118
Integration tests.

feat: updated siwe

---

src/lib.rs

Change the order in which the layers are applied to have `geoblock` at the beginning of the chain.

fix: apply geoblock at beginning of chain

---

.github/SECRETS.md

Document the secrets for updated CI pipeline.
Resolves #131 
By updating the secrets to these values and manually running CI.

chore: document secrets

---

terraform/ecs/cluster.tf
terraform/ecs/cluster_iam.tf
terraform/ecs/variables.tf
terraform/postgres/outputs.tf
terraform/res_application.tf

Attaches the policy to fix RDS authentication errors.
https://walletconnect.slack.com/archives/C04JHSB53MK/p1697645784245629
Resolves #133
Not tested

fix: attach RDS IAM role policy

---

src/auth.rs
src/model/helpers.rs
src/websocket_service/handlers/notify_watch_subscriptions.rs

Implements: https://github.com/WalletConnect/walletconnect-specs/pull/167
Resolves https://github.com/WalletConnect/notify-server/issues/150

feat: add appAuthenticationKey to NotifyWatchSubscription

---

.github/workflows/sub-infra-apply.yml
.github/workflows/sub-infra-plan.yml
terraform/README.md
terraform/ecs/README.md
terraform/ecs/cluster.tf
terraform/ecs/variables.tf
terraform/res_application.tf
terraform/variables.tf

Use the org variable `OFAC_BLOCKED_COUNTRIES` to configure the deployment instead of using a hard-coded value.
Not tested

feat: fetch the list of OFAC blocked countries from GitHub variables

---

.github/workflows/dispatch_deploy.yaml
.github/workflows/dispatch_publish.yaml
.github/workflows/sub-cd.yml

Remove deployment_window check as per [discussion today](https://www.notion.so/walletconnect/Remove-deployment_windows-check-b10faeb7f44e4fee8d97ed31809625c8?pvs=4) in Rust meeting.
Resolves #172
Not tested

chore: remove deployment_window check

---

src/handlers/notify.rs
src/types.rs
tests/integration.rs

Notification icon and URL optional as per the docs: https://docs.walletconnect.com/web3inbox/sending-notifications
Resolves #175
Integration tests

fix: optional URL and icon

---

Cargo.lock
Cargo.toml

Update the utils dependency to 0.7.0

chore: update `utils` version

---

src/auth.rs
tests/integration.rs

Update CACAO statement as per the [specs](https://github.com/WalletConnect/walletconnect-specs/pull/174)
Also log the received statement in order to know safe time to delete old statements.
Resolves #181

feat: update statement

---

src/services/publisher_service/mod.rs
src/services/websocket_server/handlers/notify_delete.rs
src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/handlers/notify_update.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs

chore: prefer JSON RPC version constant

---

src/notify_message.rs
src/services/publisher_service/helpers.rs
src/services/publisher_service/mod.rs

feat: send notification ID in wc_notifyMessage

---

src/auth.rs
src/model/helpers.rs
src/services/watcher_expiration_job.rs
src/services/websocket_server/mod.rs
src/services/websocket_server/relay_ws_client.rs

Changes warn logs to error logs since these are generally catastrophic errors and should never happen.
Also add TODOs
Not tested

chore: error logs

---

src/services/publisher_service/helpers.rs
src/services/publisher_service/mod.rs
tests/integration.rs

Seems the `dead_letters_check` query takes a long time to run. And even when it's not spiking like this, it still takes the longest out of the other queries. Attempting to optimize it by not doing maths in the query, and instead leveraging the existing indexes.
Also removed an redundant `dead_letter_give_up_check` query for checking `created_at` value.

fix: optimize queries

---

src/auth.rs
tests/deployment.rs

https://github.com/WalletConnect/walletconnect-specs/pull/175

fix: update all apps statement

---

src/error.rs

Explicitly logs all 500 and 400 errors.
Not tested

fix: improve response error logging

---

src/auth.rs
src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs

Adds timing logs so we can narrow down performance bottlenecks. [Context](https://walletconnect.slack.com/archives/C044SKFKELR/p1701807833238269).
Not tested

fix: add timing traces

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml
.github/workflows/sub-ci.yml

Update share CI to 0.1.2 to fix broken release flow
N/A

feat: updated shared CI to `0.1.1`

---

src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/mod.rs

chore: refactor ingress

---

.github/workflows/dispatch_deploy.yml

Fix https://github.com/WalletConnect/notify-server/actions/runs/7174336119
Not tested

fix: dispatch_deploy workflow

---

src/services/websocket_server/handlers/notify_watch_subscriptions.rs
src/services/websocket_server/mod.rs
src/spec.rs
src/types/mod.rs
tests/deployment.rs
tests/integration.rs

chore: continue refactor tests

---

tests/integration.rs

chore: refactor noop notify endpoint

---

src/auth.rs
src/notify_message.rs
src/spec.rs
tests/integration.rs
tests/utils/mod.rs

chore: refactor notify message tests

---

src/lib.rs
src/notify_keys.rs
src/services/public_http_server/handlers/subscribe_topic.rs
src/services/publisher_service/mod.rs
src/services/websocket_server/handlers/notify_delete.rs
src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/handlers/notify_update.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs
src/services/websocket_server/mod.rs
src/utils.rs
tests/deployment.rs
tests/integration.rs

chore: remove sha256 digests

---

src/services/websocket_server/mod.rs
src/spec.rs
src/types/mod.rs
tests/deployment.rs
tests/integration.rs

chore: refactor update and delete tests

---

tests/integration.rs

chore: reduce param count remove lifetimes

---

src/auth.rs
src/error.rs
src/services/public_http_server/handlers/subscribe_topic.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs
tests/deployment.rs
tests/integration.rs

chore: type safe account and domain

---

src/config/deployed/mod.rs
src/config/local.rs
src/config/mod.rs
src/lib.rs
src/model/helpers.rs
src/rate_limit/token_bucket.rs
src/services/public_http_server/handlers/get_subscribers_v1.rs
src/services/public_http_server/handlers/notify_v1.rs
src/services/public_http_server/handlers/subscribe_topic.rs
src/services/websocket_server/handlers/notify_delete.rs
src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/handlers/notify_update.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs
src/state.rs
tests/deployment.rs
tests/integration.rs
tests/utils/mod.rs

- Resolves #250 
- Resolves #260
- Resolves flaky tests caused by subscribe race condition (wip reproduction [here](github.com/chris13524/relay-subscribe-publish-race-condition))
- Improve log verbosity

fix: left join scope

---

src/notify_message.rs
src/services/websocket_server/handlers/notify_delete.rs
src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/handlers/notify_update.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs
src/spec.rs
tests/deployment.rs

chore: refactor magic values

---

src/auth.rs
src/error.rs
src/model/helpers.rs
src/notify_message.rs
src/services/websocket_server/handlers/mod.rs
src/services/websocket_server/handlers/notify_get_notifications.rs
src/services/websocket_server/mod.rs
src/spec.rs
tests/integration.rs

Implements https://github.com/WalletConnect/walletconnect-specs/pull/183
Resolves # (issue)

feat: notify get notifications

---

src/model/helpers.rs
tests/integration.rs

Fixes that the history was in the wrong order.
Integration tests

fix: history reversed

---

.github/workflows/sub-ci.yml
docker-compose.storage.yml
src/auth.rs
src/lib.rs
src/model/helpers.rs
src/model/types/mod.rs
src/notify_keys.rs
src/services/websocket_server/handlers/notify_delete.rs
src/services/websocket_server/handlers/notify_get_notifications.rs
src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/handlers/notify_update.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs
src/utils.rs
tests/integration.rs

Implements `sbs` in `subscribe`, `update`, and `delete` responses
Resolves #259 
New integration tests

feat: sbs response

---

terraform/monitoring/panels/lb/error_5xx.libsonnet

Getting junk unknown errors from ELB.
Resolves #270 
Not tested

fix: increase ELB 5xx error tolerance

---

src/model/helpers.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs
tests/integration.rs

Consolidate a large amount of SQL.
Tests

chore: remove mostly dup function

---

src/services/websocket_server/handlers/notify_watch_subscriptions.rs
tests/integration.rs

Fixes that watchSubscriptions, subscribe, update, and delete responses didn't return the same `account` that the request used in order to properly emulate that subscriptions are on all chains.
[Context](https://walletconnect.slack.com/archives/C044SKFKELR/p1705175551860999)
New tests.

fix: responses not updating accounts

---

src/auth.rs
src/services/websocket_server/error.rs
src/services/websocket_server/handlers/notify_delete.rs
src/services/websocket_server/handlers/notify_get_notifications.rs
src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/handlers/notify_update.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs

Working towards: https://github.com/WalletConnect/notify-server/issues/285

fix: attribute JWT errors to client

---

terraform/monitoring/panels/app/http_request_latency.libsonnet
terraform/monitoring/panels/app/relay_incoming_message_latency.libsonnet
terraform/monitoring/panels/app/relay_incoming_message_rate.libsonnet
terraform/monitoring/panels/app/relay_incoming_message_server_errors.libsonnet
terraform/monitoring/panels/rds/cpu.libsonnet
terraform/monitoring/panels/rds/freeable_memory.libsonnet

fix: more alarms

---

src/services/publisher_service/helpers.rs

Fix performance of query. [Context](https://walletconnect.slack.com/archives/C058RS0MH38/p1705976322727639?thread_ts=1705975000.738199&cid=C058RS0MH38)
Using `EXPLAIN ANALYZE`

fix: notification publish select inefficient

---

src/services/publisher_service/helpers.rs

Avoids the use of database locks and transactions which are seemingly expensive.
Resolves https://github.com/WalletConnect/notify-server/issues/321
Existing tests, and `ANALYZE EXPLAIN` with the new queries.

fix: inefficient query

---

migrations/20240123221209_index-where-status-queued.sql

Fixes pick subscriber notification query performance.
Manually in database clone: https://walletconnect.slack.com/archives/C04JHSB53MK/p1706047028996639?thread_ts=1706041983.546179&cid=C04JHSB53MK

fix: query perf

---

terraform/monitoring/panels/rds/cpu.libsonnet
terraform/monitoring/panels/rds/database_connections.libsonnet
terraform/monitoring/panels/rds/freeable_memory.libsonnet
terraform/monitoring/panels/rds/volume_bytes_used.libsonnet

As per @arein 's suggestions: https://github.com/WalletConnect/notify-server/pull/329#discussion_r1464074662
Not tested

fix: prefer max/min for alarms

---

src/publish_relay_message.rs

Instead of waiting a full second before retrying the first time, retry immediately. Most failures only happen once or twice so this avoids unnecessary latency from a transient failure.
New tests

fix: relay exponential backoff

---

src/publish_relay_message.rs

Just refactoring the logs a little bit. Prefer logging details in the span rather than in each log statement.
Not tested

fix: prefer span logs

---

.github/workflows/sub-cd.yml
.github/workflows/sub-ci.yml

Resolves https://github.com/WalletConnect/notify-server/actions/runs/7788733490/job/21239193927
Not tested

fix: deploy PAT

---

src/services/websocket_server/mod.rs

Fixes that noop (4050) message to extend topic TTL from 5m to 30d was not being published for subscriptions. The previous approach was intentional, as publishing to every subscription topic will take a long time (calculated 30-50 minutes for current number of topics) and additionally the noop message was already being published whenever the subscription was created for the first time.
However, while the noop message was already published when a subscription was created, this only increased the topic TTL to 30 days temporarily and after 30 days the topic was back to having only a TTL of 5 minutes. The topic still needs messages flowing over it for the topic to be renewed to 30 days.
[Slack conversation](https://walletconnect.slack.com/archives/C03SMNKLPU0/p1707142307187359)
Not tested

fix: noop not published for subscription topics

---

src/metrics.rs
src/publish_relay_message.rs
terraform/monitoring/panels/app/relay_outgoing_message_failures.libsonnet
terraform/monitoring/panels/app/relay_subscribe_failures.libsonnet

`permenant` -> `permanent`
Not tested

fix: spelling error

---

justfile

Submodule update checks are quick, and this makes sure we are on the right submodule version for the particular branch one is on, automatically.
Manually

chore: auto update submodules

---

src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs

Inserts the welcome notification before responding to the subscription request. This makes more sense, as it combines the "pre action finished" things together, and this needs to be combined into the same transaction as the subscriber insertion anyways.
Existing tests

fix: move welcome notification insertion sooner

---

src/error.rs
src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs

Attributes some server errors as client errors.
Not tested

fix: attribute errors as client errors

---

terraform/res_application.tf

Reduce ECS size. We have horizontal scaling now so we can do this without risk. If this is stable, I'll probably submit a follow-up to reduce in-half again.
Not tested

fix: reduce ECS size

---

src/analytics/get_notifications.rs
src/analytics/mod.rs
src/model/helpers.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/publisher_service/mod.rs

Adds analytics for get notifications calls as per the linked issue.
Resolves #409 
Not tested

fix: get notifications analytics

---

src/analytics/mod.rs
src/auth.rs
src/error.rs
src/model/types/account_id/mod.rs
src/model/types/mod.rs
src/notify_message.rs
src/rate_limit/token_bucket.rs
src/rpc.rs
src/services/public_http_server/handlers/notify_v1.rs
src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/mod.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs
src/services/public_http_server/handlers/relay_webhook/mod.rs
src/services/publisher_service/mod.rs
src/types/mod.rs
tests/utils/relay_api.rs

Attributes some client-side errors to the client and further removes error variants from and dependence on NotifyServerError.
Existing tests

fix: attribute errors to client/server

---

src/error.rs
src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_mark_notifications_as_read.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs

Attributes more errors properly as client errors.
Not tested

fix: attribute more errors as client errors

---

renovate.json

Adds Renovate bot to automatically update dependencies.
Not tested

chore: add renovate

---

Cargo.lock
Cargo.toml
src/metrics.rs

Switches to the tagged version of utils-rs
Not tested

chore: use tagged version
