WalletConnect/notify-server

.github/workflows/release.yml

The PAT used for publishing the release no longer works presumably as it was @Rakowskiii's token. This blocked CD.
Was getting the error "GitHub release failed with status: 404" which the issues on that [action's repo](https://github.com/softprops/action-gh-release) indicated this could be PAT issue, turns it was.
According to the [docs](https://github.com/softprops/action-gh-release#-customizing), token defaults to `github.token` which should work for our needs. We would need a PAT if we want a member of our's to be marked as the author of the release (rather than GitHub bot), or if we want to make a release on a different repo. But using the default is preferable otherwise as it avoids coupling the pipeline to a user's PAT. I believe this same change can be made across all of our repos. …

fix: release PAT & CD

---

src/handlers/subscribe_topic.rs
src/handlers/webhooks/delete_webhook.rs

Changes the delete endpoint response code from 200 to 204 to reflect the fact that there is no content in the response. This matches the response of the [update endpoint](https://github.com/WalletConnect/notify-server/blob/9eac65835b257783b8dc70d00bcff4c253e27046/src/handlers/webhooks/update_webhook.rs#L33).
Resolves #22
Not tested

chore: delete response code

---

src/registry.rs

Use the new endpoint that was introduced in https://github.com/WalletConnect/explorer-api/issues/161
Resolves #43
Not tested

fix: use new registry API endpoint for validating project secret

---

.github/workflows/cd.yml

I pulled in changes from cast in #33 but looks like we disabled swift tests in notify-server repo at some point in-between. So disabling swift tests now
Resolves #46
Not tested

fix: swift validation

---

.env.example
tests/integration.rs

CD integration tests were failing and I couldn't figure out why. Turns out I was using the push subscribe tag (4006) instead of the notify subscribe tag (4000) in my integration tests 🤦. Didn't see this locally when testing because my .env was configured with DEV environment which tests against the dev environment I had deployed before, of which was still running the previous version of the app that DID still allow the push subscribe tag.
Fixed the integration tests to use correct tag, and make it harder to test against non-local to prevent this issue in the future.
Resolves #55
Locally

fix: notify subscribe tag in integration tests

---

.env.terraform.example
.github/workflows/ci_terraform.yml
.github/workflows/deploy-infra.yml
justfile
terraform/provider.tf
terraform/variables.tf

Fixes:
```
$ just lint-tf
==> Running terraform fmt
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/grafana/grafana"],
│   on provider.tf line 15, in provider "grafana":
│   15: provider "grafana" {
│ 
│ "auth": one of `auth,cloud_api_key,oncall_access_token,sm_access_token` must be specified
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/grafana/grafana"],
│   on provider.tf line 16, in provider "grafana":
│   16:   url = "https://${var.grafana_endpoint}"
│ 
│ "url": all of `auth,url` must be specified
╵
error: Recipe `tf-validate` failed with exit code 1
```
Also auto-format Terraform instead of just checking.
Resolves #57
Locally with dev env. CI not tested.

fix: tflint & auto-format

---

terraform/docdb/main.tf
terraform/docdb/variables.tf
terraform/main.tf
terraform/variables.tf
terraform/vars/dev.tfvars
terraform/vars/prod.tfvars
terraform/vars/staging.tfvars

Fix low available memory alarm by upgrading from `t4g.medium` (4GB) to `r5.large` (16GB). We use `r5` on relay and history server and `r6g` on keys server which is why I changed instance type to memory optimized (`r`).
Also fix CPU alarm. Issue was new grafonnet dashboards included references to read replicas. We didn't have read replicas, but relay and keys server did (not history), so adding them here too + for future prep. Hopefully we will switch to Postgres soon though.
Resolves #40  
Resolves #61 
Dev environment

feat: read replica & bump instance class

---

terraform/monitoring/panels/app/account_not_found.libsonnet
terraform/monitoring/panels/app/dispatched_notifications.libsonnet
terraform/monitoring/panels/app/send_failed.libsonnet
terraform/monitoring/panels/app/subscribed_client_topics.libsonnet
terraform/monitoring/panels/app/subscribed_project_topics.libsonnet

Fix Subscribed Project Topics and Subscribed Client Topics showing 0. Since these are gauge metrics and not counters, `increase()` actually breaks this as the gauges don't increase that often.
Update legend for these. Since not using `sum()` we get one metric/new legend for each revision (unique combination of labels). If we use `sum()` then there is a 2x spike during rollout as there are two revisions each with the same value. Not using `sum()` results in multiple legends. Changing from generic name to revision name to make it more clear why there are multiple colors/legends.
Update refIds to be more "programatic".
Resolves #63
By hand via prod Grafana

fix: subscribed metrics

---

Cargo.lock
Cargo.toml
src/auth.rs
src/handlers/notify.rs
src/handlers/subscribe_topic.rs
src/state.rs
src/websocket_service/handlers/notify_delete.rs
src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_update.rs
tests/integration.rs

Validates identity keys by retrieving the CACAO object from the keys server.
Also bumped ed25519-dalek to newest major version which required also bumping x25519-dalek. Not sure if this was required as I went down some wrong paths, but better to be on latest version I figure.
Resolves #45 

feat: verify keys server Cacao

---

src/websocket_service/handlers/notify_subscribe.rs
tests/integration.rs

Read 4050 on notify topic before triggering the notification itself. From test log output it seems like the notify_message tag is received before the noop 4050 one is.
I'm not sure still why this would happen, as the 4050 is sent before the subscribe_response is sent, which blocks the test from calling `/notify`. But maybe it has something to do with shared mailboxes as the 4050 is sent before the test subscribes to the topic.
Relevant test failures:
- https://github.com/WalletConnect/notify-server/actions/runs/5940223449/job/16108862783
- https://github.com/WalletConnect/notify-server/actions/runs/5941506682/job/16112951153
- https://github.com/WalletConnect/notify-server/actions/runs/5941506682/job/16113352647
Resolves #77 
Local integration tests

fix: adjust location of 4050 check to reduce test flakes

---

src/state.rs
src/types.rs
src/websocket_service/handlers/notify_delete.rs
src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_update.rs

Change query to query by account instead of topic. This updates the existing lookup_table entry with a new topic for an existing account, rather than making a new one for a new topic.
Goal is to prevent multiple topics from being created for the same account.
Resolves #26
Locally with tests

fix: assert one topic per account

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/app/subscribe_latency.libsonnet
terraform/monitoring/panels/panels.libsonnet

Adds subscribe latency metric to Grafana dashbaord.
Internet seems to say you should use `histogram_quantile()` for this, but I can't seem to figure out how to use that. Seems the problem that that `le=+Inf` on all of the values. But this query seems to do what we want anyway.
Resolves #75
Manually editing prod dashboards

feat: subscribe latency panel

---

src/state.rs
src/websocket_service/handlers/notify_subscribe.rs

Because this function was supposed to be idempotent (called from subscribe) the topic could change. However because topic was _id, _id cannot be changed. Changing from replace to delete & insert avoids changing _id and creating an entirely new record instead.
Resolves #87

fix: changing topic didn't work

---

src/error.rs
terraform/monitoring/panels/lb/error_4xx.libsonnet

4xx alarm going off when someone hits invalid endpoints getting 404s. We shouldn't really alarm on 4xx anyway, but changing it to alarm when it goes above 80% of our traffic for 30 minutes. That should be good to detect any major issues.
Resolves #79
By hand with prod dashboard

fix: alarm on percent of 4xx instead of count

---

src/auth.rs
src/handlers/notify.rs
src/handlers/subscribe_topic.rs
src/types.rs
src/websocket_service/handlers/notify_delete.rs
src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_update.rs

As per @llbartekll's [comment](https://github.com/WalletConnect/walletconnect-specs/pull/138#discussion_r1316926452), ksu is only used to authenticate client-sent JWTs.
Resolves #93

fix: ksu only used for client authentication

---

terraform/monitoring/panels/lb/error_4xx.libsonnet

Cannot make alerts based on math expressions in legacy alerting: https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/expression-queries/
We don't need to alert on 4xx anyways.
Resolves #95
Locally with dev environment

fix(cd): disable alert on math expression

---

Cargo.lock
Cargo.toml
src/auth.rs
tests/integration.rs

Required by https://github.com/WalletConnect/walletconnect-specs/pull/139
The identity key will no longer be in Cacao resources but in the audience.
Resolves #97 
Integration tests

fix: follow SIWE spec

---

src/lib.rs
src/watcher_expiration.rs

Check for watchers that need to be expired every 5 minutes.
Resolves #102
Locally with integration tests & by hand

feat: expire watchers

---

.editorconfig
.github/SECRETS.md
.github/workflows/cd.yml
.github/workflows/validate_swift.yml

Re-enables Swift integration tests. Because staging notify server uses staging registry (instead of prod), I needed to refactor the secrets/inputs so I can use a different secret for staging validation than prod validation.
Resolves #110
Not tested

fix: re-enable Swift integration tests

---

src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_watch_subscriptions.rs
src/websocket_service/mod.rs

Handles relay events in parallel, fixing the disconnect issue >95% of the time.
Needed to change from spans to instrument because spans are not async-safe.
Resolves #126

fix: handle relay events in parallel

---

.github/workflows/event_release.yaml
cog.toml

- Only release on the master branch.
- Also update to latest version of WalletConnect/actions/github/update-rust-version which fixes the version bumping of `Cargo.lock`.
- Also remove cog.toml as this was causing a custom tag prefix to be set with `v` which was incompatible with the expectations of the rest of the CD pipeline
Resolves #129
In my other PR: https://github.com/WalletConnect/notify-server/pull/113/files#diff-c279c2a7a9203ec91966935663601dd38282ad4239056808ad81e596ee606a3e

fix: only release on master branch & fix bumping of Cargo.lock version

---

terraform/monitoring/panels/lb/error_5xx.libsonnet

We have an alerting rule for 5xx with a threshold of 100 in Grafana.
To catch every 5xx and not wait until it grows so much it changed to 1.
The alert message is changed to reflect threshold changes.
Resolves #139 
Not tested.

chore: changing threshold for 5xx alerting rule

---

src/websocket_service/handlers/notify_delete.rs
src/websocket_service/handlers/notify_subscribe.rs
src/websocket_service/handlers/notify_update.rs
src/websocket_service/handlers/notify_watch_subscriptions.rs
src/websocket_service/mod.rs

This PR changes the use of `publish` from websocket client to the [HTTP relay client](https://github.com/WalletConnect/WalletConnectRust/blob/main/relay_client/src/http.rs) to solve the websocket disconnect issue.
Resolves #74
Integration test.

fix: change `publish` to use http relay client in handlers

---

Cargo.toml
src/migrate.rs
src/model/types.rs
src/model/types/account_id.rs
src/model/types/mod.rs
tests/storage.rs

Makes the migration more robust by:
- handling the situation where any related rows that should be there that are missing, by ignoring the row
- always lowercasing the AccountId, as some clients follow ERC-55 but others not
Resolves #146 
Tests

fix: robust migration

---

src/model/helpers.rs
tests/integration.rs

When watchSubscriptions is called for all domains, it doesn't get triggered when subscriptions changed because it needed to be a LEFT join in order to also include subscription_watcher rows where no associated project is found.
Resolves #154

fix: watchSubscriptions for all domains not triggering subscriptionsChanged

---

src/handlers/subscribe_topic.rs
src/model/helpers.rs
src/websocket_service/handlers/notify_watch_subscriptions.rs
tests/integration.rs

`app_authentication_key` should be a `did:key` as per the [updated spec](https://github.com/WalletConnect/walletconnect-specs/pull/167).
Resolves #152 

fix: did:key app_authentication_key

---

src/model/helpers.rs

As per the specs, account is supposed to be updated if the same did:key is used to call watchSubscriptions. Furthremore, it makes sense to update the `app` being watched, so I submitted a [specs change](https://github.com/WalletConnect/walletconnect-specs/pull/168/files) for this too.
Resolves #156 
Not tested. Not covered by automated tests.

fix: watcher account not updated

---

.github/workflows/sub-app-check.yml
Cargo.toml
deny.toml

Make sure using only permissive open source licenses.
Resolves #170
```bash
cargo deny check license
```
And CI

chore: add license check

---

src/auth.rs

Logs the JWT `iss` (the identity key public key) which helps in debugging errors. This can also help identify malicious users and block them in the Keys Server.
Resolves #179
Not tested

fix: log JWT iss

---

justfile

Disable conventional commit check because the CI check is only on PR names now, which becomes the name of the squashed commit.
`just lint`

chore: disable cog check

---

terraform/monitoring/panels/app/relay_incomming_message_server_errors.libsonnet
terraform/monitoring/panels/app/relay_outgoing_message_failures.libsonnet

Fixes alarms alarming when there is no data. Errors happen rarely so we don't expect there to be data most of the time.
Resolves # (issue)
Not tested. Copied from the other charts: https://github.com/WalletConnect/notify-server/blob/b0a7d9d56396c31673521bbdeb8aa1abe7ca69f3/terraform/monitoring/panels/lb/error_5xx.libsonnet#L25

fix: always in alarm state

---

src/metrics.rs
src/services/publisher_service/mod.rs
terraform/monitoring/panels/app/publishing_workers_count.libsonnet
terraform/monitoring/panels/app/publishing_workers_errors.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds the following metrics and Grafana panels for the [publishing workers](https://github.com/WalletConnect/notify-server/pull/141/files#diff-f98e7dc00c29834c3f756eb45b17715c24d9d98c04c3f62ee7a4e702f064cf02):
* Current spawned publishing workers count,
* Workers errors counter (increased when the worker ended up with the error). This is useful to track workers' health status.
Resolves #186 
Build and CI gate tests.

feat(metrics): adding publishing workers count and errors count

---

migrations/20231018121518_init.sql
migrations/20231025145134_add_notification.sql

Make SQL style consistent. While it's generally a bad idea to change existing migrations, these should be functionally equivalent and won't be rerun anyway because the migration ID is what determines if the migration was already run or not.
This copies the style in [echo-server](https://github.com/WalletConnect/echo-server/pull/277).
This style matches what I've generally seen in the Postgres documentation:
- lowercase type names
Furthermore, I took the liberty of explicitly specifying `NULL` constraint which is equivalent to no `NOT NULL` which I verified by checking `\d+ notification`

chore: style sql

---

src/metrics.rs
src/services/publisher_service/helpers.rs
src/services/publisher_service/mod.rs
src/services/publisher_service/types.rs
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/app/publishing_workers_processing_size.libsonnet
terraform/monitoring/panels/app/publishing_workers_published_count.libsonnet
terraform/monitoring/panels/app/publishing_workers_queued_size.libsonnet
terraform/monitoring/panels/panels.libsonnet

This PR adds metrics for message queue size and statuses:
* Current messages queue size in `queued` state,
* Current messages queue size in `processing` state,
* Counter for messages marked as `published`.
Queue sizes are collected by polling the database with the count query in a minute interval and storing the result in the observable gauge.
The published counter is populated during the message status update.
Following Grafana panels were added:
* Spawned publishing workers count (ref. #192 ),
* Publishing workers error count (ref #192 ),
* Count of messages in queued state,
* Count of messages in processing state,
* Published messages counter.
Resolves #189 
Only local smoke test.

feat(metrics): adding messages queue stats

---

src/services/publisher_service/helpers.rs

This PR adds a small refactor to use `update_message_processing_status` helper function to change the message status instead of manually running the SQL.
This is useful for tracking metrics inside the `update_message_processing_status` function and following the DRY.
* Making `update_message_processing_status only to change status` to be used with PgPool and Pg transactions,
* Refactor the place of using it.
Resolves #189
Just a build-and-up local smoke test.

refactor: using only `update_message_processing_status` to change status

---

terraform/monitoring/dashboard.jsonnet

Easier to correlate with e.g. log entries or other team members.
Not tested

fix: switch Grafana dashboard to UTC

---

terraform/monitoring/panels/app/relay_incomming_message_server_errors.libsonnet
terraform/monitoring/panels/app/relay_outgoing_message_failures.libsonnet
terraform/monitoring/panels/lb/error_5xx.libsonnet

Alarms after >0 notifications, not >1. And alarms after 0 minutes of triggering, not after 5 minutes of it triggering.
This should actually catch all errors.
Not tested

fix: alarm immediately

---

src/auth.rs
src/types/mod.rs

Empty scopes were erroring out with a UUID parse error. This fixes that.
Context: https://walletconnect.slack.com/archives/C044SKFKELR/p1700121974884859

fix: allow empty scopes

---

src/auth.rs
src/error.rs
src/services/public_http_server/handlers/subscribe_topic.rs
tests/deployment.rs
tests/integration.rs

- Fixes the server error when app domain is already taken by another project ID
- Tests the idempotency of `/subscribe-topic` endpoint
Resolves #199

fix: no 500 on app domain conflict

---

src/services/public_http_server/handlers/notify_v0.rs
src/services/public_http_server/handlers/notify_v1.rs
tests/deployment.rs
tests/integration.rs

Limits the number of accounts in a single `/notify` request to 500. This prevents the server from being overloaded with too many accounts and taking too long to process a request. Senders needing to send more than 500 must issue multiple requests to send everything. For now setting to a nice conservative 500, but we can increase this in the future. Depends on https://github.com/WalletConnect/gm-cron/pull/10
Also fixes the validation of notifications to be done before any sending takes place.
Add `notification_id` idempotency key to v0 notify endpoint so that gm-cron can use it.

fix: limit to /notify 500 notifications

---

src/services/public_http_server/handlers/notify_v1.rs
terraform/monitoring/panels/app/send_failed.libsonnet

This metric is outdated since we have the new publisher service. Any failures are now the result of an improper scope, which is a client-facing "error" and in many cases may even be normal behavior.
Not tested

fix: remove failed to send alarm

---

src/services/public_http_server/handlers/get_subscribers_v0.rs
src/services/public_http_server/handlers/get_subscribers_v1.rs
src/services/public_http_server/mod.rs
src/services/publisher_service/mod.rs

- Fixes 500 error when project not found.
- Change `make_span_with` to be INFO log (from default of DEBUG) so that "Unhandled errors" are easier to debug
- `Ok(_)` -> `Ok(())` to be explicit that nothing is being ignored

fix: propagate wrong project ID

---

src/services/publisher_service/helpers.rs
tests/integration.rs

Fixes idempotency. This would give a RowNotFound error because `DO NOTHING` results in no results. We have to `DO UPDATE` and actually update something, then `RETURNING` will give results.
Didn't have tests for this before :/

fix: notification idempotency

---

src/model/helpers.rs
src/services/public_http_server/handlers/get_subscribers_v0.rs
src/services/public_http_server/handlers/get_subscribers_v1.rs
src/services/public_http_server/handlers/notify_v1.rs
src/services/public_http_server/mod.rs
src/services/publisher_service/mod.rs
tests/integration.rs

Only selects the necessary data for the code block that calls the `get_subscribers_for_project_in()` query.
Also removes some unnecessary `.iter().cloned().collect::<HashSet<_>>()` calls and logs the notification counts for future monitoring.

fix: select less

---

src/model/helpers.rs
src/services/public_http_server/handlers/subscribe_topic.rs

Noticed we can optimize this, if we determine that we updated instead of inserted, then we don't need to subscribe.
It would be possible to do this without returning `topic`, but this would involve mucking with the private/public keypairs and would probably incur additional overhead so decided not to do it.
Not tested

fix: avoid redundant subscribe

---

Cargo.lock
Cargo.toml
src/config/local.rs
src/error.rs

Fixes `cargo audit`. Only remaining issue is `openssl` but there is no fix version:
```
Crate:     rsa
Version:   0.9.3
Title:     Marvin Attack: potential key recovery through timing sidechannels
Date:      2023-11-22
ID:        RUSTSEC-2023-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0071
Severity:  7.4 (high)
Solution:  No fixed upgrade is available!
Dependency tree:
rsa 0.9.3
└── sqlx-mysql 0.7.2
├── sqlx-macros-core 0.7.2
│   └── sqlx-macros 0.7.2
│       └── sqlx 0.7.2
│           └── notify-server 0.13.9
└── sqlx 0.7.2
error: 1 vulnerability found!
```
Work performed:
- Switch `dotenv` with unmaintained warning to `dotenvy`
- Remove `atty` with security warning, not used
- Remove unused `async-tungstenite`; version needed to be bumped alongside `tungstenite`
- …

fix: security audits

---

.github/workflows/dispatch_deploy.yml

Due to the chain of dependencies, the CD step was not run when only deploying infra.
This should fix the issue.
N/A

fix: run `CD` phase of dispatched deploy when only infra is selected

---

Cargo.lock
Cargo.toml
src/services/public_http_server/mod.rs

Adds `x-request-id` header span to make it easier to follow requests. [Context](https://github.com/WalletConnect/blockchain-api/commit/ab0a84a1a2a14230f189549fb3cfe1df9dbaec26#r134832094).
Not tested

fix: add x-request-id

---

terraform/inputs.tf

The `data-lake` workspace has been renamed to `datalake` on TFC, which breaks TF operations.
This updated the name of the data source to reflect those changes.
TF plan.

fix: update the name of the `datalake` state source.

---

src/model/helpers.rs
src/notify_message.rs
src/services/publisher_service/mod.rs
tests/integration.rs

Adds `sent_at` field as per the [specs](https://github.com/WalletConnect/walletconnect-specs/pull/183#pullrequestreview-1811112546)
Integration tests

feat: history sent_at

---

src/model/helpers.rs
tests/integration.rs

Actually reverses the order of get notifications so that the most recently sent notification is ordered first in the list.
Updated tests

fix: history order

---

README.md
justfile
migrations/20240111200929_unique_account_address.sql
src/auth.rs
src/error.rs
src/model/helpers.rs
src/services/websocket_server/handlers/notify_delete.rs
src/services/websocket_server/handlers/notify_subscribe.rs
src/services/websocket_server/handlers/notify_update.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs
src/utils.rs
tests/integration.rs
tests/utils/mod.rs

- Implements behavior for treating any account the same as long as it has the same address. This works by using the `get_address_lower()` function when doing SQL queries.
- An alternative approach is to migrate the database so that it only stores address and not the full account ID. While this would simplify queries and probably be simpler overall, I decided to keep the current format as this is a risky change overall and the chain info may be needed in the future (for example with smart contract support or namespace identification).
- For now assumes eip155 account IDs
- Manually confirmed that all accounts are currently eip155
- This is enforced going forward with `is_eip155_account()` in the `verify_identity()` function
- Implements migration to delete subscribers with the same …

feat: chain agnostic

---

src/model/helpers.rs
src/services/websocket_server/handlers/notify_subscribe.rs
tests/integration.rs

Fixes that calling subscribe multiple times will send multiple welcome notifications.
Resolves #275 

fix: subscribe twice sends 2 welcome notifications

---

terraform/monitoring/README.md
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/main.tf
terraform/monitoring/panels/app/postgres_query_rate.libsonnet
terraform/monitoring/panels/app/relay_incoming_message_server_errors.libsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/monitoring/variables.tf
terraform/res_application.tf
terraform/res_monitoring.tf

Adds Grafana charts for Redis and bump scaling configuration to match current scale.
Resolves #281
Not tested

fix: add Redis Grafana and bump scale

---

src/auth.rs
src/services/websocket_server/handlers/notify_watch_subscriptions.rs

Increase 4010 rate limit and add JWT validity period leeway.
[Context](https://walletconnect.slack.com/archives/C044SKFKELR/p1705465288509419)
Not tested

fix: temp boost watch subscriptions rate limit and JWT validity allowance

---

Cargo.lock
Cargo.toml
src/services/websocket_server/mod.rs

This limits the relay subscription concurrency to prevent huge database request spikes on reconnections. Also makes use of the new 'blocking' subscriptions. See https://github.com/WalletConnect/WalletConnectRust/pull/56 and https://github.com/WalletConnect/rs-relay/pull/1387.
Untested.

feat: limit subscription concurrency

---

deny.toml

Fixes CI failure from updated cargo-check version. E.g. https://github.com/WalletConnect/notify-server/actions/runs/7595391279/job/20687904506?pr=299
N/A

fix: CC0-1.0 not found

---

src/services/public_http_server/handlers/notify_v1.rs
tests/integration.rs

Fix that `/notify` endpoint returned the original account IDs rather than the ones uses in the request.
New tests

fix: chain agnostic notify response

---

terraform/monitoring/panels/app/publishing_workers_count.libsonnet
terraform/monitoring/panels/app/publishing_workers_errors.libsonnet
terraform/monitoring/panels/app/publishing_workers_processing_size.libsonnet
terraform/monitoring/panels/app/publishing_workers_published_count.libsonnet
terraform/monitoring/panels/app/publishing_workers_queued_size.libsonnet

The counts double during a deployment because of `sum`. Standardize on showing separate graphs for all metrics.
Also update legend format to show revision # like the other charts, and remove unused refIds.
Not tested

fix: show separate metrics per replica

---

terraform/monitoring/panels/app/http_request_latency.libsonnet

`GET /subscribers` endpoint is known slow due to inefficiency of downloading all subscribers and is causing [alarms](https://walletconnect.slack.com/archives/C058RS0MH38/p1705848849714019).
This PR disables the alarm for this endpoint as it will always be slow. Some other improvements must be made though to have performance overall: https://github.com/WalletConnect/notify-server/issues/309
Not tested

fix: don't alarm on get subscribers endpoint

---

src/services/websocket_server/mod.rs

Reduce time it takes to subscribe to relay topics
Not tested

fix: 4x subscribe request concurrency

---

.github/workflows/dispatch_deploy.yml

This PR fixes the error on the manual dispatch of the [`Deploy` workflow](https://github.com/WalletConnect/notify-server/actions/workflows/dispatch_deploy.yml) with the default `- current -` image tag by making the following changes:
* Making the `Release Version` as an option with the following options:
* `current` - current deployed image tag.
* `latest` - latest release tag.
* `manual` - manual image tag version to deploy.
* Using the manual tag only when the `manual` option is chosen.
Tested by invoking the workflow from the branch in the same workflow in the `blockchain-api`:
* [Current](https://github.com/WalletConnect/blockchain-api/actions/runs/7609402830)
* [Latest](https://github.com/WalletConnect/blockchain-api/actions/runs/7609486525/job/20720834815#step:1:37)
* …

fix(ci): using the `current`, `latest` or `manual` image tag in the manual deploy

---

terraform/monitoring/panels/app/relay_incoming_message_rate.libsonnet

This was alarming when rate went below 1/s but we want to see when the count goes to <1 not the rate <1
Manually in Grafana

fix: alarm when count in last 5 minutes less than 1 not rate less than 1/s

---

src/services/public_http_server/handlers/notify_v1.rs

Make sure we are sending back the right results. There should be exactly 1 status for each input account. Will manually check logs for this error.
Not tested

fix: assert correct response counts

---

terraform/monitoring/panels/lb/error_5xx.libsonnet

Got [an alarm](https://walletconnect.slack.com/archives/C058RS0MH38/p1705635750741479) but the ELB errors cannot be identified. Adjusting the threshold.
Not tested

fix: adjust ELB 500 threshold

---

terraform/monitoring/panels/app/relay_incoming_message_rate.libsonnet

Alarm was firing because there were other lines without the data. Add `sum` so any line/metric will count as traffic.
Manually in Grafana

fix: 4010 alarm

---

.github/workflows/dispatch_deploy.yml

This PR reduces the fetch depth for looking at the latest tags to omit the old formatted `v` suffixed tags.
The depth size `15` should be enough to omit the old tags and to get the commit in the list with the latest tag.
Run this action from this branch: [Successfully got the latest version tag](https://github.com/WalletConnect/notify-server/actions/runs/7623522352/job/20763733615#step:1:38).

fix(ci): reducing fetch depth to omit old tags

---

.github/workflows/event_pr.yml
justfile
tests/deployment.rs
tests/integration.rs
tests/utils/mod.rs

Switches from websocket to HTTP for tests. Websocket client is not well-tested and seems to have bugs. Simplify to use HTTP polling.
Itself

fix: use relay HTTP client for tests

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/main.tf
terraform/monitoring/panels/rds/cpu.libsonnet
terraform/monitoring/panels/rds/database_connections.libsonnet
terraform/monitoring/panels/rds/freeable_memory.libsonnet
terraform/monitoring/panels/rds/volume_bytes_used.libsonnet
terraform/monitoring/variables.tf
terraform/res_monitoring.tf

Fixes that the RDS charts include databases that aren't part of this TF deployment (e.g. manual clones).
Somewhat manually via Grafana.

fix: only show metrics for the deployed database

---

src/model/helpers.rs
src/services/public_http_server/handlers/subscribe_topic.rs

Reverts #230 
This was flawed for several reasons:
- The subscribe could fail to complete in the relay because we are not yet using blocking subscriptions
- The subscription expires after 5 minutes without any messages
- ~~The subscription expires after 30 days (no resubscribes for this anywhere!!)~~ Edit: we subscribe upon reconnection to the relay, but this does assume a reconnect takes place at least once every 30 days.
Not tested

fix: notify server not subscribed

---

src/auth.rs
src/model/types/account_id.rs
tests/integration.rs
tests/utils/mod.rs

Calling `/notify` with an invalid AccountId (e.g. just an address w/o chain prefix) will trigger a panic at https://github.com/WalletConnect/notify-server/blob/85edd887622ad0a1e7a9a96e7a73794202e3d323/src/utils.rs#L23
This is because the AccountId is not validated in request payloads.
Update the logic to enforce this at the AccountId construction level. Switch from `new_type!` macro which bypasses try_from and implement custom serde deserializer.
New test case.

fix: panic when calling /notify with invalid AccountId

---

src/services/publisher_service/mod.rs

This PR increased the number of publishing workers from `30` to `50`.
Not tested.

feat: increasing publishing workers count to 50

---

src/services/public_http_server/handlers/notify_v1.rs
src/types/notification.rs
terraform/monitoring/panels/rds/cpu.libsonnet
tests/integration.rs

- Raises RDS CPU alarm from max 70% to 90%
- Adds test case that optional notification fields are indeed optional
- Logs an info whenever we are inserting the allowed maximum number of subscriber notifications to analyze its performance and if the limit should be increased
Existing tests

fix: raise RDS CPU alarm threshold, tests, extra logging

---

src/model/helpers.rs
src/publish_relay_message.rs
src/services/public_http_server/handlers/subscribe_topic.rs
src/services/websocket_server/handlers/notify_subscribe.rs
tests/integration.rs

Fixes that project topic from the database wasn't being used to subscribe to, and also sends a noop tag to ensure the relay topic will last for 30 days instead of just 5 minutes.
New test

fix: ensure subscription to project topic

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/app/publishing_workers_count.libsonnet
terraform/monitoring/panels/app/publishing_workers_errors.libsonnet
terraform/monitoring/panels/app/publishing_workers_processing_size.libsonnet
terraform/monitoring/panels/app/publishing_workers_published_count.libsonnet
terraform/monitoring/panels/app/publishing_workers_queued_size.libsonnet

Renames the publishing workers charts to be a little bit friendlier
Not tested

chore: rename charts

---

tests/integration.rs
tests/utils/mod.rs

Need to resubscribe the `mpsc` (via cloning the RelayClient) another time or else there's a race condition where the second accept_watch_subscriptions_changed doesn't receive the message because the first accept_watch_subscriptions_changed stole it.
N/A

fix: flaky tests

---

.gitmodules
src/publish_relay_message.rs
src/services/public_http_server/handlers/subscribe_topic.rs
src/services/websocket_server/mod.rs

When https://github.com/WalletConnect/notify-server/pull/333 was shipped it didn't account for existing projects. The assumption was that projects could fix by performing `subscribe-topic`, however this is a long tail so should be fixed for good.
Not tested

fix: publish noop to existing project topics

---

.github/workflows/sub-ci.yml
.gitmodules
README.md
docker-compose.storage.yml
justfile
src/config/local.rs
src/registry/storage/redis/mod.rs
tests/deployment.rs
tests/integration.rs

Builds and runs rs-relay locally and uses it for tests instead of the deployed relay. This sets the stage for switching to webhooks for incoming relay messages.
This seems to greatly improve on test flakyness.
Existing tests.

fix: test with local relay

---

src/services/publisher_service/helpers.rs

[Context](https://walletconnect.slack.com/archives/C04JHSB53MK/p1706457674290119?thread_ts=1706041983.546179&cid=C04JHSB53MK)
Prevents a race condition in picking a notification to send where the same notification can be picked up by multiple workers before it is marked as processing.
Also adds the missing update_at change which regressed when I rewrote the query.
Not tested

fix: pick notification race condition

---

.github/workflows/sub-ci.yml
terraform/.terraform-docs.yml
terraform/README.md
terraform/alerting/README.md
terraform/docdb/README.md
terraform/ecs/README.md
terraform/monitoring/README.md
terraform/postgres/README.md
terraform/redis/README.md

Fixes that in the latest Terraform version the Markdown table would have lots of whitespace prefixing the lines.
[Context](https://walletconnect.slack.com/archives/C068RRL89HC/p1706311832813029)
Depends on https://github.com/WalletConnect/ci_workflows/pull/1
N/A

fix: tfdocs indent

---

.github/workflows/sub-cd.yml
.github/workflows/sub-ci.yml
src/services/websocket_server/mod.rs
src/state.rs

[This PR](https://github.com/WalletConnect/notify-server/pull/349) fixed that topic subscriptions may expire after a period of time, however it allowed this renewal operation to run in parallel. However in-parallel can result in high levels of load on the relay and we don't need it to run in parallel.
This PR prevents this from running in parallel if one operation is already running.
[Slack conversation](https://walletconnect.slack.com/archives/C058RS0MH38/p1707250697304959?thread_ts=1707250104.976949&cid=C058RS0MH38)
Not tested

fix: only run renew operation one at a time

---

src/services/relay_renewal_job/refresh_topic_subscriptions.rs

Removes the blocking subscribe from startup. Because we've switched to webhooks, we do not need to associate the subscription with the websocket, and the relay will remember the subscription for 30 days. We still need to renew, so that async job is still there. This will be improved with #325 
Improving startup time allows the service to start, which apparently it isn't starting anymore due to the length of time it takes to subscribe being longer than the healthcheck allowance: https://walletconnect.slack.com/archives/C058RS0MH38/p1707770358630189?thread_ts=1707766935.771459&cid=C058RS0MH38
Not tested

fix: don't block startup on subscribe

---

src/model/types/account_id.rs

Resolves #364 
We should be enforcing ERC-55 not normalizing to it. Log if there is non-compliance at all and if we are safe to enforce.
Not tested

fix: log if an address is ERC-55 or not

---

src/services/public_http_server/handlers/relay_webhook/mod.rs

Searching for why a 5xx happened should be easy. I search for "HTTP server error" but the relay webhook was doing a different error response than the main error handler.
In the future we should share the same `IntoResponse for Error` as the other HTTP endpoints, but for now just re-using the same string prefix.
Not tested

fix: use common log for HTTP errors

---

src/model/types/account_id.rs
tests/integration.rs
tests/utils/mod.rs

Followup to #364. CAIP-10 [requires the use of ERC-55](https://github.com/ChainAgnostic/namespaces/blob/main/eip155/caip10.md#syntax), and until now we have been permissive about this and normalized to ERC-55 internally. However, we should follow the spec and require ERC-55 now so people don't get lazy in the future.
This PR updates the logic to require ERC-55 to construct an `AccountId`. If this fails validation, an error will be returned to the appropriate party.
Logs show that the only non-compliance with ERC-55 is in the use of the `/notify` endpoint from 1 obscure project with 0 subscribers, and 1 client that appeared today. I decided not to build backwards-compatibility for these 2 entities.
Also I manually checked that all existing database rows are all eip155 accounts and are …

fix: enforce ERC-55 addresses

---

src/services/public_http_server/handlers/relay_webhook/mod.rs

Paired with https://github.com/WalletConnect/rs-relay/pull/1448 this debugs long delays in delivering webhooks.
[Slack conversation](https://walletconnect.slack.com/archives/C044SKFKELR/p1708610471719339)
Not tested

fix: log relay message

---

tests/utils/mod.rs

Timeout doesn't need to be this long, and reducing it allows us to catch regressions in performance
N/A

fix: reduce test timeout

---

src/services/relay_mailbox_clearing_service.rs

Calling `batch_receive()` takes some time, and at high request throughputs (if `req/s / 500 > call time OR call time > batch_timeout`) this channel can block and increase request latency. Doesn't seem like an issue now (we have low req/s), and we don't know for sure because we don't have metrics on this request (yet). But increasing it preemptively as memory is not a problem.
Not tested

fix: increase channel size

---

Cargo.toml
src/auth.rs
src/model/types/account_id/eip155.rs
src/model/types/account_id/mod.rs
src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs
tests/deployment.rs
tests/integration.rs
tests/utils/mod.rs
tests/utils/notify_relay_api.rs
tests/utils/relay_api.rs

Handles the Keys Server 404 error as a client error. Also refactors all the identity verification error handling logic to be an internal vs client error.
Introduced shared `test_utils` as a regular module as both integration tests (which are not `#[cfg(test)]`) and unit tests use it.
Resolves #327 
New test case

fix: attribute Keys Server 404 as client error

---

src/error.rs
src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs

Attributes unknown topic errors as client errors. Also removes a lot of unused error variants from `NotifyServerError`
Resolves #373
Not tested

fix: unknown topic client error

---

src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs
src/services/public_http_server/handlers/relay_webhook/mod.rs

Logs this info for debugging. Also changes the ordering to more align with how these values will be validated in the future.
Also logs JSON-RPC info as oftentimes debuggers give me JSON-RPC ID instead of message ID.
Not tested

fix: log whu, sub, aud, and JSON-RPC info

---

src/auth.rs
src/error.rs
src/model/helpers.rs
src/services/public_http_server/handlers/get_subscribers_v0.rs
src/services/public_http_server/handlers/get_subscribers_v1.rs
src/services/public_http_server/handlers/get_welcome_notification.rs
src/services/public_http_server/handlers/notify_v1.rs
src/services/public_http_server/handlers/post_welcome_notification.rs
src/services/public_http_server/mod.rs
src/types/notification.rs
tests/integration.rs

Updates the v1 endpoint (has never been called and is not documented) to the new scalable endpoint as described in https://github.com/WalletConnect/walletconnect-docs/pull/1391
Also changes some 400 errors to 422 errors since this is a more appropriate error code.
Resolves #352 
Updated and new test cases

feat: get subscribers v1

---

terraform/ecs/cluster.tf
terraform/ecs/cluster_autoscaling.tf
terraform/postgres/main.tf
terraform/res_application.tf

- Downscales prod ECS task CPU and memory by half. CPU and memory has been idling around <5% except for spikes up to around 30%. Halving this to reduce cost and lean into horizontal scaling soon.
- Downscales staging deployment by setting min capacities to their minimum for non-prod deployments:
- Minimum CPU + memory as possible
- Minimum RDS ACUs as possible
- Single replica minimum (when we enable HA + HS we'll have 2 as the minimum here)
- Refactor task CPU calculation to make task memory be the main app + otel sidecar size. Prev: needed to do math to see which size to use.
Not tested

fix: downscale

---

terraform/monitoring/panels/app/http_request_latency.libsonnet
terraform/monitoring/panels/app/relay_incoming_message_latency.libsonnet

Processing a relay message takes a while and often has been triggering alarms. There are strategies to reduce this we are implementing, but ultimately this metric does not represent user-experienced latency so not worth alarming on it at a low threshold.
Not tested

fix: increase relay latency alarm threshold

---

migrations/20240227222554_index_subscription_watcher_account.sql
src/error.rs
src/model/helpers.rs
src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs
tests/integration.rs

Adds a limit to the number of subscription watchers that can be registered at once. It limits to 25 watchers per project value, which means that each app_domain can have up to 25 watchers, and for watchers without a project specified can also have a maximum of 25 (e.g. app.web3inbox.com, wallets, mis-configured apps).
Looking at our data, it seems like there is no more than 13 of these at once. But more than 2-3 seems very odd in the first place.
For context: watchers also expire after 1 day.
New test case.

fix: limit subscription watcher count

---

terraform/ecs/cluster.tf
terraform/ecs/variables.tf

Enables autoscaling to have horizontal scalability and sets a min capacity of 2 to have high availability.
Also fixes that desired count wasn't being set to 1 in non-prod.
Blocked by #388 ([explanation](https://github.com/WalletConnect/notify-server/issues/362#issuecomment-1965422922))
Resolves #362 
Not tested

fix: enable autoscaling

---

src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs

Performs the response publish and the watcher publishes all in parallel (with a concurrency limit of 11). The goal being to get watch updates to watchers faster, and to reduce our overall latency metric for processing incoming relay messages.
Resolves #266 
Existing tests. Latency metrics will be improved but latency is not tested automatically until we have a latency canary.

fix: publish response and subscription watcher updates in parallel

---

terraform/postgres/variables.tf

Fixes alarms that we are using more than half of our RDS CPU. This is caused by an [inefficiency in the send notification queue](https://github.com/WalletConnect/notify-server/issues/320). This will be resolved, but we can work around the alarms for now by increasing the ACUs.
Not tested

fix: increase RDS max capacity to handle spikes in message sending

---

src/notify_message.rs
src/services/publisher_service/mod.rs
terraform/postgres/README.md
tests/utils/notify_relay_api.rs

Fixes that notify message `app` field didn't use a `did:web` as per [the specs](https://specs.walletconnect.com/2.0/specs/clients/notify/authentication#wc_notifymessage-request).
As per [this discussion](https://walletconnect.slack.com/archives/C044SKFKELR/p1703388140774189) no clients depend on the current behavior, so while this is a breaking change it should not affect anything.
Resolves #251 
Updated tests

fix: notify message should use did:web

---

src/auth.rs
src/siwx/erc5573.rs
terraform/postgres/README.md

As per [clarified spec](https://github.com/ethereum/ERCs/pull/303), having multiple ReCap URIs in Resources is not allowed. This is a programming error so should be rejected.
New test case

fix: require one ReCap URI

---

Cargo.lock
Cargo.toml
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs

Update to latest Rust SDK version in order to use new blocking relay functions that return errors.
[Slack conversation](https://walletconnect.slack.com/archives/C03SMNKLPU0/p1710163595419859)
Existing tests

fix: update to latest Relay SDK version

---

src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs
src/services/public_http_server/handlers/relay_webhook/mod.rs
src/services/public_http_server/mod.rs

- Remove the headers from the request span to reduce logging cost. Only include x-request-id in request span. All other details are logged once at the beginning of request processing.
- Fix that running locally request spans would not show because log level is `WARN,notify_server=DEBUG` and the span was in an external crate
- Remove random `client_public_key` log
Resolves #387 
Locally

fix: reduce logging overhead

---

src/rpc.rs
src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs
src/services/publisher_service/mod.rs
src/types/mod.rs
tests/deployment.rs
tests/integration.rs
tests/utils/notify_relay_api.rs
tests/utils/relay_api.rs

Sends JSON-RPC error responses when an error is encountered wherever possible rather than not responding at all.
Remaining work:
Resolves #15 
Updated automated tests

fix: error responses

---

src/publish_relay_message.rs

Logs how long it took for a relay error to occur. Determines if errors tend to occur immediately (in which case the existing retries solve that) or after 5s+ (in which case adding timeouts will help).
Not tested

fix: log relay error elapsed time

---

src/model/helpers.rs

Fixes some errors:
- `sqlx error: error returned from database: could not serialize access due to concurrent update`
- `sqlx error: error returned from database: could not serialize access due to read/write dependencies among transactions`
Not tested

fix: serialization errors

---

.github/workflows/dispatch_deploy.yml
.github/workflows/dispatch_publish.yml
.github/workflows/event_intake.yml
.github/workflows/event_pr.yml
.github/workflows/event_release.yml
.github/workflows/sub-cd.yml
.github/workflows/sub-ci.yml
.github/workflows/sub-validate-health.yml
.github/workflows/sub-validate-rust.yml

Updates the runners to use `ubuntu-latest` since they were using `ubuntu-runners` group unnecessarily which is expensive.
Remaining work:
Not tested

fix: use ubuntu-latest runner

---

justfile

`tf-fmt` already formats, we don't need this in `fmt` too. `fmt` should just be for cargo
Manually

chore: remove redundant terraform fmt

---

terraform/ecs/README.md
terraform/ecs/outputs.tf
terraform/monitoring/README.md
terraform/monitoring/dashboard.jsonnet
terraform/monitoring/main.tf
terraform/monitoring/panels/lb/error_5xx.libsonnet
terraform/monitoring/panels/lb/error_5xx_logs.libsonnet
terraform/monitoring/panels/panels.libsonnet
terraform/monitoring/variables.tf
terraform/res_monitoring.tf

Restructures the Grafana a little bit to bring 5xx errors to the top. Lower priority of subscribed topics/latency, also this metric seems to have broken at some point.
Adds HTTP 5xx errors to Grafana so it's easy to jump to them.
Remaining work:
Resolves #286  
Resolves #358 
Not tested

fix: grafana 5xx errors

---

src/services/publisher_service/mod.rs
tests/integration.rs

Since the worker count was only incremented _after_ spawning the worker, it was possible for the worker spawning loop to spawn more workers than it should. So I refactored the incrementing to take place before spawning.
Also consolidate `load` and `fetch_add|sub`. Since `fetch_*` returns the previous value, we can apply the operation non-atomically to get the resulting value and avoid the second atomic load.
Also relax the ordering from `SeqCst`. I read up on ordering [in the docs](https://doc.rust-lang.org/nomicon/atomics.html) and I think I did it right.
Also refactor `notification_for_delivery` magic string.
Resolves #319 
No new tests because this is a race condition and tough to test.

fix: worker count going above limit

---

terraform/monitoring/dashboard.jsonnet
terraform/monitoring/panels/lb/error_4xx.libsonnet
terraform/monitoring/panels/lb/error_5xx_logs.libsonnet

Fixes that the error logs cell was disabling as a timeseries rather than a table.
Fixes that the dashboard cells were wider than they were supposed to be.
Not tested

fix: Grafana error logs table

---

src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs

Fixes that client or server errors emitted inside of the `handle()` functions were not being returned from the main handler function and thus were not logged or recorded in metrics.
Not tested

fix: errors being excluded from metrics and not being logged

---

Cargo.lock
Cargo.toml
migrations/20240319001421_is_read.sql
src/analytics/mark_notifications_as_read.rs
src/analytics/mod.rs
src/auth.rs
src/model/helpers.rs
src/notify_message.rs
src/services/public_http_server/handlers/relay_webhook/error.rs
src/services/public_http_server/handlers/relay_webhook/handlers/mod.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_mark_notifications_as_read.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs
src/services/public_http_server/handlers/relay_webhook/mod.rs
src/services/publisher_service/helpers.rs
src/services/publisher_service/mod.rs
src/spec.rs
tests/integration.rs

Implements support for marking notifications as read as per the [specs](https://github.com/WalletConnect/walletconnect-specs/pull/191).
Resolves #425 
Subsequent PRs will address the remaining TODOs at the end of integration.rs
New tests

feat: read state

---

src/model/helpers.rs
src/services/public_http_server/handlers/mark_all_as_read.rs
src/services/public_http_server/handlers/mod.rs
src/services/public_http_server/mod.rs
tests/integration.rs

Implements the `/mark-all-as-read` endpoint as per [the docs](https://github.com/WalletConnect/walletconnect-docs/pull/1376/files#diff-0f8ab41b3b114a3a0dbb28e71db638870aa01d7c93f38a94b3aeb77692a9d8deR211)
Resolves #428 
New tests

feat: mark all as read endpoint

---

src/publish_relay_message.rs

Make the logged time consistently ms. Analyzing the logs is currently harder because it can use any unit it wants.
Not tested

fix: log relay latency consistently

---

src/analytics/mod.rs
src/analytics/relay_request.rs
src/publish_relay_message.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_delete.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_get_notifications.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_mark_notifications_as_read.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_update.rs
src/services/public_http_server/handlers/relay_webhook/handlers/notify_watch_subscriptions.rs
src/services/public_http_server/handlers/relay_webhook/mod.rs
src/services/publisher_service/mod.rs

Implements a data export that links relay requests to their responses. This allows is to better understand relay data on Notify-related messages and see user-experienced latency better.
Not tested

fix: request linking

---

terraform/postgres/main.tf

CD is failing because AWS upgraded the Postgres version and it's no longer in-sync: https://github.com/WalletConnect/notify-server/actions/runs/8494688010/job/23270258501
Not tested

fix: postgres version

---

.github/workflows/event_release.yml

Bumping a dependency version or other configuration in Cargo.* or fixing something in a GitHub workflow doesn't trigger a release. The intention here was to avoid redundant deploys that weren't necessary, but this has caused more problems than it has solved over the months.
Not tested

fix: less ignores for release

---

src/metrics.rs

Fixes this error in scraping metrics:
```
Failed to parse metrics e=Msg("MetricFamily has no name: name: \"\" help: \"\" type: HISTOGRAM metric {label {name: \"otel_scope_name\" value: \"notify-server\"} histogram {sample_count: 2 sample_sum: 226 bucket {cumulative_count: 0 upper_bound: 0}
```
This looks like extra validation that the prometheus client [applies to the binary format](https://github.com/tikv/rust-prometheus/blob/f49c724df0e123520554664436da68e555593af0/src/encoder/mod.rs#L34). It seems to expect that the `Stream` has a name. We could set the names ourselves, but `new_view()` automatically inherits the instrument name, so using that instead.
Locally

fix: MetricFamily has no name

---

.github/workflows/sub-cd.yml

Fixes that when doing deploys (either by hand or from a release), if an infra deploy was required, it wouldn't deploy the new app version (if required) at all.
Not tested

fix: if deploy-infra was set deploy-app would do nothing

---

src/auth.rs
src/siwx/erc5573.rs

ERC-5573 requires that `att` keys be URIs, but our [own Sign 2.5 API isn't properly following this spec](https://walletconnect.slack.com/archives/C03RVH94K5K/p1713799617021109?thread_ts=1712839862.846379&cid=C03RVH94K5K). This PR temporarily allows this invalid value to unblock the team while we sort out a proper solution.
Also adjusts an error message to be [a little more understandable](https://walletconnect.slack.com/archives/C044SKFKELR/p1713785630296359?thread_ts=1713782285.406459&cid=C044SKFKELR).
New test case

fix: allow non-standard eip155 att key

---

src/auth.rs
src/services/relay_renewal_job/register_webhook.rs
terraform/README.md

Switches the webhook status from queued to accepted since this is subject to additional performance optimizations. [Slack conversation](https://walletconnect.slack.com/archives/C03SMNKLPU0/p1714141690313319?thread_ts=1713941199.429849&cid=C03SMNKLPU0)
Existing tests

fix: switch watcher status to queued

---

src/services/public_http_server/handlers/relay_webhook/mod.rs
src/services/relay_renewal_job/register_webhook.rs

Fixes this issue raised by Ivan:
> hey, regarding the [`queued` -> `accepted` change in notify server that you made](https://github.com/WalletConnect/notify-server/pull/526): there's a problem now with how the messages are removed using the irn_batchReceive where the message may not yet be in the mailbox when notify tries to remove it
Solution as suggested is to subscribe to both. When `accepted` is received, handle the message. And when `queued` is received, remove the message from the relay mailbox.
Existing tests

fix: only remove from mailbox after queued event

---

src/analytics/get_notifications.rs
src/analytics/mark_notifications_as_read.rs
src/analytics/notification_link.rs
src/analytics/subscriber_notification.rs
src/analytics/subscriber_update.rs

Adds the raw account ID to the analytics export. This is already included in our [privacy policy](https://walletconnect.com/privacy) so no changes are necessary there.
Not tested

fix: account analytics
